default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-yaml
        exclude: '\.*conda/.*'
      - id: end-of-file-fixer
        exclude: '\.bumpversion\.cfg'
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: debug-statements
      - id: check-added-large-files

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.38.0"
    hooks:
      - id: markdownlint

  - repo: https://github.com/populationgenomics/pre-commits
    rev: "v0.1.3"
    hooks:
      - id: cpg-id-checker

  - repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.2
    hooks:
      - id: ruff

    # Static type analysis (as much as it's possible in python using type hints)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.8.0"
    hooks:
      - id: mypy
        additional_dependencies:
          [
            types-Deprecated,
            types-frozendict,
            types-PyYAML==6.0.4,
            types-requests,
            types-tabulate,
            types-toml,
          ]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
