{% set data=load_setup_py_data() %}

package:
  name: cpg-utils
  version: {{ data['version'] }}

source:
  path: ../../

build:
  number: 0
  noarch: python

requirements:
  host:
    - python
  run:
    - python
    - google-api-python-client

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
