name: Docker
on:
  # Building on pull-requests, manual dispatch, and pushes to main; but restricting
  # publishing only to main pushes and manual dispatch with `if`s in specific steps.
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  VERSION: 4.8.12

jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      DOCKER_TAG: australia-southeast1-docker.pkg.dev/cpg-common/images/cpg_utils:$VERSION
    steps:
    - uses: actions/checkout@main

    - id: gcloud auth
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GH_IMAGES_DEPLOYER_JSON }}
  
    - name: set up gcloud sdk
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: cpg-common

    - name: gcloud docker auth
      run: |
        gcloud auth configure-docker australia-southeast1-docker.pkg.dev

    - name: build
      run: 
        docker build -f docker/Dockerfile \
        --build-arg VERSION=$VERSION \
        --tag $DOCKER_TAG docker

    - name: push
      run: docker push $DOCKER_TAG
