name: Lint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        cache: 'pip'
  
    - name: pre-commit
      run: |
        pip install pre-commit pylint
        pre-commit run --all-files

    - name: Run tests
      run: python -m unittest test/test_analysis_runner.py
