name: Lint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: requirements-lint.txt

    - name: Install packages
      run: pip install -r requirements-lint.txt

    - name: pre-commit
      run: pre-commit run --all-files
