name: Test
on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: requirements-dev.txt

    - name: Install packages
      run: pip install . -r requirements-dev.txt

    - name: "Run unit tests"
      id: runtests
      run: |
        coverage run -m unittest discover -p 'test*.py' -s '.'
        rc=$?
        coverage xml

        echo "rc=$rc" >> $GITHUB_OUTPUT

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: populationgenomics/cpg-utils

    - name: Fail if tests are not passing
      if: ${{ steps.runtests.outputs.rc != 0 }}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('Unit tests failed with rc = ${{ steps.runtests.outputs.rc }}')
