name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: requirements-dev.txt

    - name: Install packages
      run: pip install . -r requirements-dev.txt

    - name: "Run unit tests"
      id: runtests
      run: |
        coverage run -m pytest --junitxml=test-execution.xml
        rc=$?
        coverage xml

        echo "rc=$rc" >> $GITHUB_OUTPUT

    - name: 'Save coverage report as an Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./coverage.xml

    - name: 'Save execution report as an Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: execution-report
        path: ./test-execution.xml

    - name: Fail if tests are not passing
      if: ${{ steps.runtests.outputs.rc != 0 }}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('Unit tests failed with rc = ${{ steps.runtests.outputs.rc }}')
